# Generated by Django 3.1.1 on 2020-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0004_testmonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
